services:
  - type: web
    name: portfolio-backend
    runtime: node
    plan: free
    buildCommand: ./build.sh
    startCommand: node backendportfolio/server.js
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        value: https://ujjalpandey.com.np
        sync: false
