services:
  - type: web
    name: portfolio-backend
    runtime: node
    plan: free
    buildCommand: cd backendportfolio && npm install
    startCommand: cd backendportfolio && npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: EMAIL_USER
        sync: false
      - key: EMAIL_PASS
        sync: false
      - key: FRONTEND_URL
        sync: false
